''' cadastrar o usuario para um empresa e '''
nome= str(input("Qual seu nome? "))
cpf= float(input("Digite seu CPF: "))
rg= float(input("Digite o seu RG: "))
nascimento= input("Data de nascimento: ")
sexo= str(input("Selecione seu sexo: "))
peso= float(input("Peso: "))
sanguineo= str(input("Tipo sanguineo: "))
renda= float(input("Renda mensal: "))
endereco= str(input("Digite seu endereço: "))
telefone= float(input("Insira seu telefone: "))
cidade= str(input("Insira sua cidade: "))
estado= str(input("Insira seu estado: "))
print("\nNome:", nome,"\nCPF:",cpf,"\nRG:",rg,"\nData de nascimento:",nascimento, "\nSexo:",sexo, "\nPeso:", peso, "\nTipo Sanguineo:", sanguineo, "\nRenda mensal:", renda, "\nEndereço:",endereco, "\nTelefone:", telefone, "\nCidade:", cidade, "\nEstado:", estado)
